name: redstone_mvc
version: 0.2.0-beta.1 
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: MVC Plugin for Redstone
homepage: https://github.com/redstone-dart/redstone-mvc-plugin
environment:
  sdk: '>=1.9.1'
documentation: https://github.com/redstone-dart/redstone-mvc-plugin
dependencies:
  mustache: '>=0.2.2 <0.3.0'
  path: '>=1.3.5 <2.0.0'
  redstone: '>=0.6.0-beta.1+3 < 0.7.0'
  redstone_mapper: '>=0.2.0-beta.1 < 0.3.0'
  shelf: '>=0.6.0 <0.7.0'

