name: redstone_mvc
version: 0.0.380+2
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: MVC Plugin for Redstone
homepage: https://github.com/redstone-dart/redstone-mvc-plugin
environment:
  sdk: '>=1.9.1'
documentation: https://github.com/redstone-dart/redstone-mvc-plugin
dependencies:
  mustache: '>=0.2.2 <0.3.0'
  path: '>=1.3.5 <2.0.0'
  redstone: '>=0.5.0 <0.6.0'
  redstone_mapper: '>=0.1.13 <0.2.0'
  shelf: '>=0.5.7 <0.6.0'
